name: Flutter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3' # Explicit version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Run tests
    # - name: Run tests
    #   run: flutter test
